[package]
name = "tensor_types_proc"
version = "1.0.0"
edition = "2021"
description = "Support proc_macro for the tensor_types crate"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.67"
quote = "1.0.33"
syn = "2.0.37"
tch = "0.13.0"
thiserror = "1.0.49"
