[package]
name = "tensor_types_proc"
version = "0.9.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.67"
quote = "1.0.33"
syn = "2.0.37"
tch = "0.13.0"
thiserror = "1.0.49"
